### ISSUE TITLE
The mod wasn't deleted.

### ISSUE THREAD

**Issue by dsp2003** [naehc/clf-phx#1]
It's currently hosted at Nexus along with all derivative micromods that previously has their own pages: http://www.nexusmods.com/starbound/mods/585/?

A lot of negative stuff happened at Chucklefish forums lately. I was literally forced out of there along with all my work and got banned because of false accusations by Sayter. Yep, he went that far.

The official repository is located here: https://github.com/clef-starbound/clef/

Rather than making independent repository, feel free to push any changes you may find of value there. :)

**Comment by naehc** [comment]
Very good to hear that it wasn't actually deleted! :) Apparently I was misremembering the URL to the official repo, as I got 404s when trying to reach it after seeing the mod's page at CF was gone; thus my mistaken belief that it was removed from here as well. I'll shut down this standalone repository shortly, since the idea was to keep the files accessible (for future compatibility updates etc), and there's no need for a rebirth when the original fish remains alive (or... undead, what with the choking?). ;)
